# #################################
# Parameters of the final model
#
# Authors:
#  * Heitor Guimarães 2021
#  * Miguel Arjona    2021
#  * Wesley Beccaro   2021
# #################################

seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Set up folders for reading from and writing to
# .strftime ['%Y%m%d_%H%M%S']
exp_name: fcn40_55epchs_prcpt_stoiloss_ft_460h
data_folder: ../dataset
output_folder: !ref ../logs/<exp_name>
model_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
audio_result: !ref <output_folder>/audio_results
npy_result: !ref <output_folder>/npy_results

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json
train_folder: [!ref <data_folder>/L3DAS_Task1_train100, !ref <data_folder>/L3DAS_Task1_train360]
valid_folder: !ref <data_folder>/L3DAS_Task1_dev
test_folder: !ref <data_folder>/L3DAS_Task1_test

# logs with training statistics
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Training Parameters
max_train_sample_size: 32000    # Maximum number of samples to use during train
number_of_epochs: 55
batch_size: 16
learning_rate: 0.0001
dataloader_options:
    batch_size: !ref <batch_size>
test_dataloader_options:
    batch_size: 1

# Model construction
m_depth: 1                      # model depth ==> depth of Wave-U-Net / Use 1 if FCN
model: !new:mlsp_challenge.models.FCN
    in_channels: 8
    out_channels: 1
    kernel_size: 55
    base_channels: 40
    use_sinc: False
# m_depth: 7                      # model depth ==> depth of Wave-U-Net / Use 1 if FCN
# model: !new:mlsp_challenge.models.SEWUNet
#     depth: !ref <m_depth>

loss: !new:mlsp_challenge.losses.PerceptualLoss
    PRETRAINED_MODEL_PATH: '../models/wav2vec_large.pt'
    alpha: 5

modules:
    model: !ref <model>
    loss: !ref <loss>

# Optimizer parameters
opt_class: !name:torch.optim.Adam
    lr: !ref <learning_rate>
    weight_decay: 0.1

# Save state of the training process
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <model_folder>
    recoverables:
        model: !ref <model>
        counter: !ref <epoch_counter>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>