# #################################
# Parameters of the final model
#
# Authors:
#  * Heitor Guimarães 2021
#  * Miguel Arjona    2021
#  * Wesley Beccaro   2021
# #################################

seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Set up folders for reading from and writing to
# .strftime ['%Y%m%d_%H%M%S']
exp_name: first_version
data_folder: ../dataset
output_folder: !ref ../logs/<exp_name>
model_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
train_folder: !ref <data_folder>/L3DAS_Task1_train100
valid_folder: !ref <data_folder>/L3DAS_Task1_dev

# logs with training statistics
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>